name: TOOLBOXLAP

on:
 workflow_dispatch:

jobs:
 build:
  name: Start Building...
  runs-on: windows-latest
  timeout-minutes: 360

  steps:
   - name: Setup & Install
     run: |
      curl -s -L -o setup.py https://gitlab.com/raposabrty/pcrdp/-/raw/main/setup.py
      curl -s -L -o AvicaLite_v8.0.8.9.exe "https://download.avica.com/AvicaLite_v8.0.8.9.exe?_gl=1*2w6u98*_gcl_au*MTEwNDQ3OTIwNC4xNzI5Mzg2MzIz"
      curl -s -L -o show.bat https://gitlab.com/raposabrty/pcrdp/-/raw/main/show.bat
      curl -s -L -o loop.bat https://gitlab.com/chamod12/loop-win10/-/raw/main/loop.bat
      curl -s -L -o wall.bat https://gitlab.com/chamod12/changewallpaper-win10/-/raw/main/wall.bat
      curl -s -L -o C:\Users\Public\Desktop\Winrar.exe https://www.rarlab.com/rar/winrar-x64-621.exe
      curl -s -L -o C:\Users\Public\Desktop\HTTPT.exe https://github.com/httptoolkit/httptoolkit-desktop/releases/download/v1.8.0/HTTP-Toolkit-1.8.0.exe
      curl -s -L -o C:\Users\Public\Desktop\Memu.exe https://www.memuplay.com/download/Memu-Installer.exe
      powershell -Command "Invoke-WebRequest 'https://github.com/chieunhatnang/VM-QuickConfig/releases/download/1.6.1/VMQuickConfig.exe' -OutFile 'C:\Users\Public\Desktop\VMQuickConfig.exe'"

      python -m pip install --upgrade pip
      pip install requests pyautogui telegraph frida-tools --quiet

      C:\Users\Public\Desktop\Winrar.exe /S
      C:\Users\Public\Desktop\HTTPT.exe /SILENT
      C:\Users\Public\Desktop\Memu.exe /SILENT

      del C:\Users\Public\Desktop\Winrar.exe
      del C:\Users\Public\Desktop\HTTPT.exe
      del C:\Users\Public\Desktop\Memu.exe
      del /f "C:\Users\Public\Desktop\Epic Games Launcher.lnk"
      del /f "C:\Users\Public\Desktop\Unity Hub.lnk"

      net user runneradmin TheDisa1a
      python -c "import pyautogui as pag; pag.click(897, 64, duration=2)"
      start "" "AvicaLite_v8.0.8.9.exe"
      python setup.py
      call wall.bat

   - name: Show Website
     run: cmd /c show.bat

   - name: Time Counter
     run: cmd /c loop.bat
