name: gringo.rdp

on:
 workflow_dispatch:

jobs:
 build:
  name: Start Building...
  runs-on: windows-latest
  timeout-minutes: 360

  steps:
   - name: Setup & Install
     shell: pwsh
     run: |
      curl -s -L -o setup.py https://gitlab.com/raposabrty/pcrdp/-/raw/main/setup.py
      curl -s -L -o AvicaLite_v8.0.8.9.exe "https://download.avica.com/AvicaLite_v8.0.8.9.exe?_gl=1*2w6u98*_gcl_au*MTEwNDQ3OTIwNC4xNzI5Mzg2MzIz"
      curl -s -L -o show.bat https://gitlab.com/raposabrty/pcrdp/-/raw/main/show.bat
      curl -s -L -o loop.bat https://gitlab.com/chamod12/loop-win10/-/raw/main/loop.bat
      curl -s -L -o wall.bat https://gitlab.com/chamod12/changewallpaper-win10/-/raw/main/wall.bat
      curl -s -L -o C:\Users\Public\Desktop\Winrar.exe https://www.rarlab.com/rar/winrar-x64-621.exe
      curl -s -L -o C:\Users\Public\Desktop\HTTPT.exe https://github.com/httptoolkit/httptoolkit-desktop/releases/download/v1.20.1/HttpToolkit-1.20.1.exe
      curl -s -L -o C:\Users\Public\Desktop\Memu.exe https://www.memuplay.com/download-new.php?from=online2_installer
      Invoke-WebRequest 'https://github.com/chieunhatnang/VM-QuickConfig/releases/download/1.6.1/VMQuickConfig.exe' -OutFile 'C:\Users\Public\Desktop\VMQuickConfig.exe'

      python -m pip install --upgrade pip
      pip install requests pyautogui telegraph frida-tools --quiet

      Start-Process -FilePath "C:\Users\Public\Desktop\Winrar.exe" -ArgumentList "/S" -Wait
      Start-Process -FilePath "C:\Users\Public\Desktop\HTTPT.exe" -ArgumentList "/SILENT" -Wait
      Start-Process -FilePath "C:\Users\Public\Desktop\Memu.exe" -ArgumentList "/SILENT" -Wait

      Remove-Item C:\Users\Public\Desktop\Winrar.exe -Force
      Remove-Item C:\Users\Public\Desktop\HTTPT.exe -Force
      Remove-Item C:\Users\Public\Desktop\Memu.exe -Force
      Remove-Item "C:\Users\Public\Desktop\Epic Games Launcher.lnk" -Force -ErrorAction SilentlyContinue
      Remove-Item "C:\Users\Public\Desktop\Unity Hub.lnk" -Force -ErrorAction SilentlyContinue

      net user runneradmin TheDisa1a
      python -c "import pyautogui as pag; pag.click(897, 64, duration=2)"
      Start-Process -FilePath ".\AvicaLite_v8.0.8.9.exe"
      python setup.py
      cmd /c wall.bat

   - name: Show Website
     run: cmd /c show.bat

   - name: Time Counter
     run: cmd /c loop.bat
