name: gringo.rdp

on:
 workflow_dispatch:

jobs:
 build:
  name: Start Building...
  runs-on: windows-latest
  timeout-minutes: 360

  steps:
   - name: Setup & Install
     shell: pwsh
     timeout-minutes: 15
     run: |
      Write-Host "Downloading required files..."
      curl -s -L -o setup.py https://gitlab.com/raposabrty/pcrdp/-/raw/main/setup.py
      curl -s -L -o AvicaLite_v8.0.8.9.exe "https://download.avica.com/AvicaLite_v8.0.8.9.exe?_gl=1*2w6u98*_gcl_au*MTEwNDQ3OTIwNC4xNzI5Mzg2MzIz"
      curl -s -L -o show.bat https://gitlab.com/raposabrty/pcrdp/-/raw/main/show.bat
      curl -s -L -o loop.bat https://gitlab.com/chamod12/loop-win10/-/raw/main/loop.bat
      curl -s -L -o wall.bat https://gitlab.com/chamod12/changewallpaper-win10/-/raw/main/wall.bat
      Write-Host "Downloads completed."

      Write-Host "Installing Python packages..."
      python -m pip install --upgrade pip
      pip install requests pyautogui telegraph frida-tools --quiet
      Write-Host "Python packages installed."

      Write-Host "Setting up user account..."
      net user runneradmin TheDisa1a

      Write-Host "Starting Avica..."
      python -c "import pyautogui as pag; pag.click(897, 64, duration=2)"
      Start-Process -FilePath ".\AvicaLite_v8.0.8.9.exe"
      
      Write-Host "Running setup script..."
      python setup.py
      
      Write-Host "Setting wallpaper..."
      cmd /c wall.bat

   - name: Show Website
     timeout-minutes: 5
     run: cmd /c show.bat

   - name: Time Counter
     timeout-minutes: 330
     run: cmd /c loop.bat
